language: node_js
node_js:
- '4'
- '6'
- '8'
before_install:
- npm i -g npm
notifications:
  email: false
  slack:
    rooms:
      secure: JwpvcSTp9SI+BOgknqy7dZ8lVdasS1n4CtUc4H2Hw1LULGg5Bb6JDoYO+fR4iNE2qyX2rkE6U+mqlVUGaZNBSUSPh3qqeSBKgU0zUQ323R/fpj+dSMP/XfIGu73nKEUAJhRBL3mfDLOEdybWf8IvLbXrDpeDZku1C+N2/NnmocAQCA5wN7H3rSrKwg2G2+5f/JPMUrVwit9eskIycWQU5XRJAy4kptHHOL9vTDs3DKd9bJ4sasoVNvusjKUGcG/fMLdZRDiVVtLqShUbxk2Bzx02hvQcA67UYgpfCPvUoCNFtW5i1qDyxGej6uLrg6T2rZdGNTBCfF1U/iVycgZcsGKhX1Ji06lWVaHSkaRyVysH7eZ6YPB+7AWEZX5QJ/LOgAcNEcA9g69NukIZmiMe4Kv/R6s+7wGAa+ezs22QwXAW9C3cP187TOSqtHqF0X79IGY1ne8gGj6Bl1eKc04lzDUIhVtFdMjzgCb6j0ON/8DvZlBuCImXLtxK6OK54wdEZvFuPks+iOoDRI7OuQSeji7qPzdee+NdTj8AEoHh9iRr7J+jSIuCaxIOZD62wD5phYONBPb92zbjUvAabmc9p6DEKmCKP1CSqyfnKV4S0S3fBXRJ7JFzuD+tRppjtaJXeblYsDuKevlyYHGCm7xLT4HkOoie7cT+2sj5qmmuvCI=
