language: node_js
node_js:
- '4'
- '6'
- '8'
before_install:
- npm i -g npm
- npm i -g nyc codecov
script:
- nyc npm test
after_success:
- nyc report --reporter=text-lcov > coverage.lcov
- codecov
notifications:
  email: false
